version: 0.2
phases:
  install:
    runtime-versions:
      java: openjdk11
    run-as: root
    commands:
      - echo This is a installation
      - wget https://services.gradle.org/distributions/gradle-4.6-all.zip
      - unzip -d /opt/gradle gradle-4.6-all.zip
  pre_build:
    commands:
      - echo This is a pre build
  build:
    commands:
      - echo Starting build `date`
      - echo Current directory is `pwd`
      - whereis gradle
      - which gradle
      - cd web
      - /opt/gradle/gradle-4.6/bin/gradle -version
      - /opt/gradle/gradle-4.6/bin/gradle clean
      - /opt/gradle/gradle-4.6/bin/gradle build
  post_build:
    commands:
      - echo Build must be completed
artifacts:
  files:
    - '**/*'
  discard-paths: no